apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image.name }}
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
          - name: QUARKUS_DATASOURCE_JDBC_URL
            value: "jdbc:mysql://{{ .Release.Name }}-mysql.{{ .Release.Namespace }}.svc.cluster.local:3306/database"
          - name: QUARKUS_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{ .Release.Name }}-mysql"
                key: mysql-password
          - name: QUARKUS_DATASOURCE_USERNAME
            value: {{ .Values.mysql.auth.username }}
        envFrom:
          - secretRef:
              name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.app.port }}
