apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: {{ .Values.app.image.name }}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: QUARKUS_PROFILE
            value: k8s
        envFrom:
          - secretRef:
              name: {{ .Values.app.name }}
        ports:
        - containerPort: {{ .Values.app.port }}
